### ISSUE TITLE
更改包路径

### ISSUE THREAD

**Issue by wurangbo** [pengfeidai/gin-app-start#1]
我想把
import (
	"context"
	"fmt"
	"gin-app-start/app/common"
	"gin-app-start/app/config"）
改成
import (
	"context"
	"fmt"
	"xxx/app/common"
	"xxx/app/config"）

需要怎么修改？

**Comment by 0xdpfly** [comment]
可以在 go.mod 文件中更改，然后全局将gin-app-start进行替换



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "wurangbo"<notifications@github.com&gt;; 
发送时间: 2021年3月5日(星期五) 下午2:05
收件人: "pengfeidai/gin-app-start"<gin-app-start@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [pengfeidai/gin-app-start] 更改包路径 (#1)





 
我想把
 import (
 "context"
 "fmt"
 "gin-app-start/app/common"
 "gin-app-start/app/config"）
 改成
 import (
 "context"
 "fmt"
 "xxx/app/common"
 "xxx/app/config"）
 
需要怎么修改？
